#define CURLYBEGIN 1
#define CURLYEND 2
#define BRACKETBEGIN 3
#define BRACKETEND 4
#define VARNAME 5
#define COMMA 6
#define SEMICOLON 7
#define SQUAREBEGIN 8
#define SQUAREEND 9
#define INTEGER 10
#define UNEXPECTED 11
#define SPACE 12
#define TABSPACE 13
#define NEWLINE 14
#define ENTRY 15

#define PARAM 16
#define LOCAL 17
#define REG 18
#define MOV 19
#define CONVERT 20 //cvta
#define MEMOP 21
#define LOAD 22
#define COMP 23
#define Store 24
#define CONTROLFLOW 25
#define BRANCH 26
#define CALL 27
#define RET 28
#define EXIT 29
#define BAR 30
#define MEMBAR 31
#define DOT 32
#define STORE 33
#define SHARED 34
#define GLOBAL 35
#define DIRECTIVE 36
#define COLON 37
